# Generated by Django 4.0.8 on 2023-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('price_range', models.CharField(choices=[('cheap', 'Cheap'), ('affordable', 'Affordable'), ('expensive', 'Expensive')], max_length=12)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
